<?php

use Illuminate\Database\Seeder;

class CmsMenusTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('cms_menus')->delete();
        
        \DB::table('cms_menus')->insert(array (
            0 => 
            array (
                'id' => 5,
                'name' => 'Public',
                'type' => 'Route',
                'path' => 'AdminPublicControllerGetIndex',
                'color' => 'normal',
                'icon' => 'fa fa-users',
                'parent_id' => 0,
                'is_active' => 1,
                'is_dashboard' => 0,
                'id_cms_privileges' => 1,
                'sorting' => 3,
                'created_at' => '2018-12-06 10:11:13',
                'updated_at' => '2018-12-10 10:54:59',
            ),
            1 => 
            array (
                'id' => 11,
                'name' => 'Freins',
                'type' => 'Route',
                'path' => 'AdminFreinsControllerGetIndex',
                'color' => 'normal',
                'icon' => 'fa fa-ban',
                'parent_id' => 0,
                'is_active' => 1,
                'is_dashboard' => 0,
                'id_cms_privileges' => 1,
                'sorting' => 5,
                'created_at' => '2018-12-06 14:39:02',
                'updated_at' => '2018-12-10 10:55:10',
            ),
            2 => 
            array (
                'id' => 12,
                'name' => 'Rendez vous',
                'type' => 'Route',
                'path' => 'AdminRdvControllerGetIndex',
                'color' => 'normal',
                'icon' => 'fa fa-calendar-plus-o',
                'parent_id' => 0,
                'is_active' => 1,
                'is_dashboard' => 0,
                'id_cms_privileges' => 1,
                'sorting' => 4,
                'created_at' => '2018-12-06 15:09:45',
                'updated_at' => '2018-12-10 10:55:20',
            ),
            3 => 
            array (
                'id' => 13,
                'name' => 'Accueil Libre',
                'type' => 'Route',
                'path' => 'AdminAccueilLibreControllerGetIndex',
                'color' => 'normal',
                'icon' => 'fa fa-home',
                'parent_id' => 0,
                'is_active' => 1,
                'is_dashboard' => 0,
                'id_cms_privileges' => 1,
                'sorting' => 1,
                'created_at' => '2018-12-10 10:55:45',
                'updated_at' => '2018-12-10 11:16:16',
            ),
            4 => 
            array (
                'id' => 16,
                'name' => 'Statistiques Situations',
                'type' => 'Statistic',
                'path' => 'statistic_builder/show/suivis-de-situations',
                'color' => 'normal',
                'icon' => 'fa fa-th-large',
                'parent_id' => 0,
                'is_active' => 1,
                'is_dashboard' => 0,
                'id_cms_privileges' => 1,
                'sorting' => 6,
                'created_at' => '2018-12-11 13:38:23',
                'updated_at' => '2018-12-12 13:21:14',
            ),
            5 => 
            array (
                'id' => 17,
                'name' => 'Statistiques Emploi',
                'type' => 'Statistic',
                'path' => 'statistic_builder/show/statistiques-premiere-rencontre',
                'color' => 'normal',
                'icon' => 'fa fa-th-large',
                'parent_id' => 0,
                'is_active' => 1,
                'is_dashboard' => 0,
                'id_cms_privileges' => 1,
                'sorting' => 7,
                'created_at' => '2018-12-11 13:39:16',
                'updated_at' => '2018-12-12 12:47:52',
            ),
            6 => 
            array (
                'id' => 18,
                'name' => 'Contact',
                'type' => 'Statistic',
                'path' => 'statistic_builder/show/contact',
                'color' => 'normal',
                'icon' => NULL,
                'parent_id' => 16,
                'is_active' => 1,
                'is_dashboard' => 0,
                'id_cms_privileges' => 1,
                'sorting' => 5,
                'created_at' => '2018-12-12 09:17:48',
                'updated_at' => '2018-12-12 13:22:05',
            ),
            7 => 
            array (
                'id' => 19,
                'name' => 'Activités',
                'type' => 'Statistic',
                'path' => 'statistic_builder/show/activites',
                'color' => 'normal',
                'icon' => NULL,
                'parent_id' => 16,
                'is_active' => 1,
                'is_dashboard' => 0,
                'id_cms_privileges' => 1,
                'sorting' => 6,
                'created_at' => '2018-12-12 09:18:25',
                'updated_at' => '2018-12-12 13:22:13',
            ),
            8 => 
            array (
                'id' => 20,
                'name' => 'Freins',
                'type' => 'Statistic',
                'path' => 'statistic_builder/show/freins-observe',
                'color' => 'normal',
                'icon' => NULL,
                'parent_id' => 16,
                'is_active' => 1,
                'is_dashboard' => 0,
                'id_cms_privileges' => 1,
                'sorting' => 2,
                'created_at' => '2018-12-12 09:18:53',
                'updated_at' => '2018-12-12 13:21:35',
            ),
            9 => 
            array (
                'id' => 21,
                'name' => 'Freins selon âge',
                'type' => 'Statistic',
                'path' => 'statistic_builder/show/freins-selon-tranche-dage',
                'color' => 'normal',
                'icon' => NULL,
                'parent_id' => 16,
                'is_active' => 1,
                'is_dashboard' => 0,
                'id_cms_privileges' => 1,
                'sorting' => 3,
                'created_at' => '2018-12-12 09:20:27',
                'updated_at' => '2018-12-12 13:21:42',
            ),
            10 => 
            array (
                'id' => 22,
                'name' => 'Lieux intervention',
                'type' => 'Statistic',
                'path' => 'statistic_builder/show/lieux-dintervention',
                'color' => 'normal',
                'icon' => NULL,
                'parent_id' => 16,
                'is_active' => 1,
                'is_dashboard' => 0,
                'id_cms_privileges' => 1,
                'sorting' => 4,
                'created_at' => '2018-12-12 09:21:07',
                'updated_at' => '2018-12-12 13:21:54',
            ),
            11 => 
            array (
                'id' => 23,
                'name' => 'Personnes par jour',
                'type' => 'Statistic',
                'path' => 'statistic_builder/show/personnes-par-jour',
                'color' => 'normal',
                'icon' => NULL,
                'parent_id' => 17,
                'is_active' => 1,
                'is_dashboard' => 0,
                'id_cms_privileges' => 1,
                'sorting' => 7,
                'created_at' => '2018-12-12 09:21:29',
                'updated_at' => '2018-12-12 12:49:36',
            ),
            12 => 
            array (
                'id' => 24,
                'name' => 'Répartition par âge',
                'type' => 'Statistic',
                'path' => 'statistic_builder/show/repartition-par-age',
                'color' => 'normal',
                'icon' => NULL,
                'parent_id' => 17,
                'is_active' => 1,
                'is_dashboard' => 0,
                'id_cms_privileges' => 1,
                'sorting' => 10,
                'created_at' => '2018-12-12 09:23:42',
                'updated_at' => '2018-12-12 12:49:21',
            ),
            13 => 
            array (
                'id' => 25,
                'name' => 'Répartition par genre',
                'type' => 'Statistic',
                'path' => 'statistic_builder/show/repartition-par-genre',
                'color' => 'normal',
                'icon' => NULL,
                'parent_id' => 17,
                'is_active' => 1,
                'is_dashboard' => 0,
                'id_cms_privileges' => 1,
                'sorting' => 9,
                'created_at' => '2018-12-12 09:24:35',
                'updated_at' => '2018-12-12 12:49:11',
            ),
            14 => 
            array (
                'id' => 26,
                'name' => 'Répartition profil des bénéficiaires',
                'type' => 'Statistic',
                'path' => 'statistic_builder/show/repartition-profil-des-beneficiaires',
                'color' => 'normal',
                'icon' => NULL,
                'parent_id' => 17,
                'is_active' => 1,
                'is_dashboard' => 0,
                'id_cms_privileges' => 1,
                'sorting' => 8,
                'created_at' => '2018-12-12 09:25:05',
                'updated_at' => '2018-12-12 12:49:01',
            ),
            15 => 
            array (
                'id' => 27,
                'name' => 'Personnes accueil libre',
                'type' => 'Statistic',
                'path' => 'statistic_builder/show/personnes-par-jour-accueil-libre',
                'color' => 'normal',
                'icon' => NULL,
                'parent_id' => 16,
                'is_active' => 1,
                'is_dashboard' => 0,
                'id_cms_privileges' => 1,
                'sorting' => 1,
                'created_at' => '2018-12-12 12:39:30',
                'updated_at' => '2018-12-12 13:21:26',
            ),
            16 => 
            array (
                'id' => 28,
                'name' => 'Personne accueil libre',
                'type' => 'Statistic',
                'path' => 'statistic_builder/show/personnes-par-jour-accueil-libre',
                'color' => 'normal',
                'icon' => NULL,
                'parent_id' => 17,
                'is_active' => 1,
                'is_dashboard' => 0,
                'id_cms_privileges' => 1,
                'sorting' => 6,
                'created_at' => '2018-12-12 12:50:19',
                'updated_at' => '2018-12-12 12:50:31',
            ),
            17 => 
            array (
                'id' => 29,
                'name' => 'Freins',
                'type' => 'Statistic',
                'path' => 'statistic_builder/show/freins-observe',
                'color' => 'normal',
                'icon' => NULL,
                'parent_id' => 17,
                'is_active' => 1,
                'is_dashboard' => 0,
                'id_cms_privileges' => 1,
                'sorting' => 3,
                'created_at' => '2018-12-12 12:51:12',
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'id' => 30,
                'name' => 'Freins selon âge',
                'type' => 'Statistic',
                'path' => 'statistic_builder/show/freins-selon-tranche-dage',
                'color' => 'normal',
                'icon' => NULL,
                'parent_id' => 17,
                'is_active' => 1,
                'is_dashboard' => 0,
                'id_cms_privileges' => 1,
                'sorting' => 4,
                'created_at' => '2018-12-12 12:51:32',
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'id' => 31,
                'name' => 'Lieux intervention',
                'type' => 'Statistic',
                'path' => 'statistic_builder/show/lieux-dintervention',
                'color' => 'normal',
                'icon' => NULL,
                'parent_id' => 17,
                'is_active' => 1,
                'is_dashboard' => 0,
                'id_cms_privileges' => 1,
                'sorting' => 5,
                'created_at' => '2018-12-12 12:52:27',
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'id' => 32,
                'name' => 'Contact',
                'type' => 'Statistic',
                'path' => 'statistic_builder/show/contact',
                'color' => 'normal',
                'icon' => NULL,
                'parent_id' => 17,
                'is_active' => 1,
                'is_dashboard' => 0,
                'id_cms_privileges' => 1,
                'sorting' => 2,
                'created_at' => '2018-12-12 12:52:47',
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'id' => 33,
                'name' => 'Activités',
                'type' => 'Statistic',
                'path' => 'statistic_builder/show/activites',
                'color' => 'normal',
                'icon' => NULL,
                'parent_id' => 17,
                'is_active' => 1,
                'is_dashboard' => 0,
                'id_cms_privileges' => 1,
                'sorting' => 1,
                'created_at' => '2018-12-12 12:53:07',
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'id' => 34,
                'name' => 'Statistiques accueil libre',
                'type' => 'Statistic',
                'path' => 'statistic_builder/show/personnes-par-jour-accueil-libre',
                'color' => 'normal',
                'icon' => NULL,
                'parent_id' => 0,
                'is_active' => 1,
                'is_dashboard' => 0,
                'id_cms_privileges' => 1,
                'sorting' => 2,
                'created_at' => '2018-12-12 15:01:11',
                'updated_at' => '2018-12-12 15:02:09',
            ),
        ));
        
        
    }
}